### ISSUE TITLE
无网

### ISSUE THREAD

**Issue by loeveo** [mmmdbybyd/CNS#1]
一些软件会出现无法连接网络情况，或者是无法正常的刷新，比如chrome.访问谷歌网盘的网页版就会提示访问的是离线版本.或者是刷新非常慢以及谷歌网盘app都会出现检测不到网络的情况.并且使用rclone也无法正常的连接(比如列出某个网盘内的文件列表，但是一直无法显示)Google Grive及OneDrive(包括世纪互联版)

**Comment by loeveo** [comment]
无论是通过GET还是POST请求

**Comment by mmmdbybyd** [comment]
你试试新版，或者加QQ915445800
