### ISSUE TITLE
托管脚本的网站似乎挂了

### ISSUE THREAD

**Issue by PDxtXHd** [mmmdbybyd/CNS#14]
![image](https://user-images.githubusercontent.com/54795848/128656960-2f8acea2-8b10-4e92-842d-079041d239f3.png)

**Comment by mmmdbybyd** [comment]
`type curl &>/dev/null && echo 'curl -O' || echo 'wget -O cns.sh'` http://pros.cutebi.flashproxy.cn:666/cns/cns.sh && sh cns.sh
