### ISSUE TITLE
udp

### ISSUE THREAD

**Issue by zzh151223** [mmmdbybyd/CNS#15]
免流开启udp后在服务器netstat apn可以看到连接信息，然后就无论如何再也没有了，udp也连不上。除非重新开启免流才会出现，然后又用不了udp

**Comment by mmmdbybyd** [comment]
提供更具体的情况  免流是直接连服务器  还是通过百度直连之类的代理，有没有可能是端口问题

**Comment by zzh151223** [comment]
好像是版本问题，之前都是从网上下的别人的，从这里下是正常的
