### ISSUE TITLE
手动安装的菜鸟教程，启动成功

### ISSUE THREAD

**Issue by f23997** [mmmdbybyd/CNS#19]
手动安装

**Comment by f23997** [comment]
{
	"Tcp_timeout": 300
	"Udp_timeout": 30
	"Listen_addr": [":1254"]
	"Keep_alive": 60
	"proxy_key": "Meng"
	"encrypt_password": "666"
	"Enable_dns_tcpOverUdp": true
	"Enable_httpDNS": true
	"Enable_TFO": true
}

**Comment by f23997** [comment]
{
	"Tcp_timeout": 300,
	"Udp_timeout": 30,
	"Listen_addr": [":1254"],
	"Keep_alive": 60,
	"proxy_key": "Meng",
	"encrypt_password": "666",
	"Enable_dns_tcpOverUdp": true,
	"Enable_httpDNS": true,
	"Enable_TFO": true, 
	"Tls": {
		"listen_addr": [":8978"],
		"AutoCertHosts": ["m.baidu.com", "yaohuo.me", "mymy.ip"]
	}
}

**Comment by f23997** [comment]
用的nat客户端配置文件没，用一键脚本可以连接有网

**Comment by mmmdbybyd** [comment]
把tls部分删了

**Comment by f23997** [comment]
> 把tls部分删了

删了无法启动，用了第三方修改的可以手动安装
