### ISSUE TITLE
一键脚本失效

### ISSUE THREAD

**Issue by zhangruian** [mmmdbybyd/CNS#20]
666端口的那个服务器挂掉了 一键脚本无法安装

**Comment by oneg1** [comment]
pros.cutebi.flashproxy.cn改成pros.cutebi.taobao66.cn

**Comment by oneg1** [comment]
bash <(wget -qO- https://pan.vpshax.ml/d/Teambition/CN/cns.sh?sign=c55a275792fc1d08)

**Comment by mmmdbybyd** [comment]
之前服务器被攻击了  现在改了域名，已恢复
`type curl &>/dev/null && echo 'curl -O' || echo 'wget -O builds.sh'` http://binary.quicknet.cyou/builds.sh && sh builds.sh
