### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by SaavyGirl** [mmmdbybyd/CNS#6]

**Comment by mmmdbybyd** [comment]
![QQ截图20201019160840](https://user-images.githubusercontent.com/18487473/96658460-19cf8b00-1377-11eb-8ded-f16f12ce0b9e.png)
![QQ截图20201019163309](https://user-images.githubusercontent.com/18487473/96658463-1b994e80-1377-11eb-9617-61838314c940.png)

**Comment by SaavyGirl** [comment]
Good deal
