### ISSUE TITLE
cns install failed.

### ISSUE THREAD

**Issue by threnhainan** [mmmdbybyd/CNS#7]
root@instance-3:~#  `type curl &>/dev/null && echo 'curl -O' || echo 'wget -O cns.sh'` http://pros.cutebi.taobao69.c
n:666/cns/cns.sh && sh cns.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4627  100  4627    0     0   2882      0  0:00:01  0:00:01 --:--:--  2882
Please input cns server port(If not need, please skip):  443
Please input cns encrypt password(If not need, please skip):  5201314nan
Please input cns udp flag(Defaule is 'httpUDP'):  httpUDP
Please input cns proxy key(Default is 'Meng'):  Host
Please input tls server port(If not need, please skip): 
Please input cns install directory(difault is /usr/local/cns): 
Install UPX version?[n]: 
make a update?[n]: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
unzip is already the newest version (6.0-20ubuntu1).
curl is already the newest version (7.47.0-1ubuntu2.16).
wget is already the newest version (1.17.1-1ubuntu1.5).
The following packages were automatically installed and are no longer required:
  linux-gcp-headers-4.15.0-1047 linux-gcp-headers-4.15.0-1049 linux-gcp-headers-4.15.0-1050
  linux-gcp-headers-4.15.0-1052 linux-gcp-headers-4.15.0-1055 linux-gcp-headers-4.15.0-1058
  linux-gcp-headers-4.15.0-1060 linux-gcp-headers-4.15.0-1061 linux-gcp-headers-4.15.0-1071
  linux-gcp-headers-4.15.0-1077 linux-gcp-headers-4.15.0-1078 linux-gcp-headers-4.15.0-1080
  linux-gcp-headers-4.15.0-1081 linux-gcp-headers-4.15.0-1083
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
curl is /usr/bin/curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4408k  100 4408k    0     0   734k      0  0:00:06  0:00:06 --:--:--  650k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1331  100  1331    0     0  12757      0 --:--:-- --:--:-- --:--:-- 12798
systemctl is a tracked alias for /bin/systemctl

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   315  100   315    0     0   2017      0 --:--:-- --:--:-- --:--:--  2019
cns install failed.
remove cns?[y]: y
Synchronizing state of cns.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install disable cns
insserv: warning: current start runlevel(s) (empty) of script `cns' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `cns' overrides LSB defaults (0 1 6).
insserv: warning: current start runlevel(s) (empty) of script `cns' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `cns' overrides LSB defaults (0 1 6).
cns is stopped...
root@instance-3:~#

**Comment by mmmdbybyd** [comment]
现在再安装看看，不行就加群反馈一下
